---

syntax: {}

autotools: ~

testunit: {}

basicstats: {}

notes: {}

rdoc:
  template: jamis
  inline: true

ridoc: {}

gem:
  exclude:
    - doc/rdoc
    - doc/ri

rubyforge:
  unixname: clio
  groupid: 6913
#  publishmap:
#    admin/web: .
#    doc/rdoc: rdoc

