Command Definition and Usage Output
===================================

Require commandline library.

  require 'clio/command'

Create new commandline object.

    $0 = 'test'
    @cmd = Clio::Command.new('--verbose')

Handles a command definition using #command.

    @cmd.usage.command('foo')
    @cmd.to_s.assert == 'test foo'

Handles a toplevel switch option using #option.

    @cmd.usage.option('verbose?')
    @cmd.to_s.assert == 'test [--verbose] foo'

Handles a toplevel switch option with aliases using #option.

    cmd = Clio::Command.new('--verbose')
    cmd.usage.option(:verbose?, :v)
    cmd.to_s.assert == 'test [--verbose -v]'

An option and a subcommand parsed statically.

    cmd = Clio::Command.new('-v foo')
    cmd.usage.opt('--verbose -v')
    cmd.usage.command('foo')
    cmd.to_s.assert == 'test [--verbose -v] foo'

QED.

